# fly.toml app configuration file generated for hashblog on 2025-06-10T10:56:43+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'hashblog'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 4321
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
