name = "hashblog"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
name = "hashblog"

[env.preview]
name = "hashblog-preview"

# Enable experimental features if needed
# [experimental]
# nodejs_compat = true 